function plot_dominant_v2(fd)

colors = [0.4 0.4 0.4; 0.9 0.9 0.9];
hoy = char(datetime('now','Format','yyyyMMdd'));

source_data_dominant_v2 = table();
stats_table_dominant_v2 = table();

training_phases = [1, 2, 3, 4];
phase_labels = {'2 & 2b', '3', 'Early 4', 'Late 4'};

source_data_dominant_v2 = add_section_source(source_data_dominant_v2, ...
    'All', 'Leader', training_phases, phase_labels, ...
    [4, 5, 6, 4], [10, 9, 8, 10]);

[stats_table_dominant_v2, p_binom, p_chi] = plot_one_section( ...
    fd, hoy, colors, ...
    'All', 'Leader', ...
    training_phases, phase_labels, ...
    [4, 5, 6, 4], [10, 9, 8, 10], ...
    'Dominant vs Subordinate becoming leaders', ...
    [fd 'plots/' hoy '_dominant_becoming_leaders'], ...
    stats_table_dominant_v2);

source_data_dominant_v2 = add_section_source(source_data_dominant_v2, ...
    'All', 'Initiator', training_phases, phase_labels, ...
    [4, 5, 6, 8], [10, 9, 8, 6]);

[stats_table_dominant_v2, p_binom, p_chi] = plot_one_section( ...
    fd, hoy, colors, ...
    'All', 'Initiator', ...
    training_phases, phase_labels, ...
    [4, 5, 6, 8], [10, 9, 8, 6], ...
    'Dominant vs Subordinate becoming initiators', ...
    [fd 'plots/' hoy '_dominant_becoming_initiators'], ...
    stats_table_dominant_v2);

fill_colors = [239,154,154;129,212,250]/255;
line_colors = [183,28,28;1,87,155]/255;

female_colors = [line_colors(1,:); fill_colors(1,:)];
male_colors   = [line_colors(2,:); fill_colors(2,:)];

source_data_dominant_v2 = add_section_source(source_data_dominant_v2, ...
    'Female', 'Leader', training_phases, phase_labels, ...
    [3 3 4 2], [6 6 5 7]);

[stats_table_dominant_v2, p_binom, p_chi] = plot_one_section( ...
    fd, hoy, female_colors, ...
    'Female', 'Leader', ...
    training_phases, phase_labels, ...
    [3 3 4 2], [6 6 5 7], ...
    'Dominant vs Subordinate becoming leaders', ...
    [fd 'plots/' hoy '_dominant_becoming_leaders_female'], ...
    stats_table_dominant_v2);

source_data_dominant_v2 = add_section_source(source_data_dominant_v2, ...
    'Male', 'Leader', training_phases, phase_labels, ...
    [1 2 2 2], [4 3 3 3]);

[stats_table_dominant_v2, p_binom, p_chi] = plot_one_section( ...
    fd, hoy, male_colors, ...
    'Male', 'Leader', ...
    training_phases, phase_labels, ...
    [1 2 2 2], [4 3 3 3], ...
    'Dominant vs Subordinate becoming leaders', ...
    [fd 'plots/' hoy '_dominant_becoming_leaders_male'], ...
    stats_table_dominant_v2);

source_data_dominant_v2 = add_section_source(source_data_dominant_v2, ...
    'Female', 'Initiator', training_phases, phase_labels, ...
    [2 2 3 5], [7 7 6 4]);

[stats_table_dominant_v2, p_binom, p_chi] = plot_one_section( ...
    fd, hoy, female_colors, ...
    'Female', 'Initiator', ...
    training_phases, phase_labels, ...
    [2 2 3 5], [7 7 6 4], ...
    'Dominant vs Subordinate becoming initiators', ...
    [fd 'plots/' hoy '_dominant_becoming_initiators_female'], ...
    stats_table_dominant_v2);

source_data_dominant_v2 = add_section_source(source_data_dominant_v2, ...
    'Male', 'Initiator', training_phases, phase_labels, ...
    [2 3 3 3], [3 2 2 2]);

[stats_table_dominant_v2, p_binom, p_chi] = plot_one_section( ...
    fd, hoy, male_colors, ...
    'Male', 'Initiator', ...
    training_phases, phase_labels, ...
    [2 3 3 3], [3 2 2 2], ...
    'Dominant vs Subordinate becoming initiators', ...
    [fd 'plots/' hoy '_dominant_becoming_initiators_male'], ...
    stats_table_dominant_v2);

assignin('base','source_data_dominant_v2',source_data_dominant_v2);
assignin('base','stats_table_dominant_v2',stats_table_dominant_v2);

fprintf('\nSaved to base workspace:\n')
fprintf('source_data_dominant_v2\n')
fprintf('stats_table_dominant_v2\n')

end

function source_data = add_section_source(source_data, sex_group, behavior, training_phases, phase_labels, dominant_data, subordinate_data)

T = table( ...
    repmat({sex_group},numel(training_phases),1), ...
    repmat({behavior},numel(training_phases),1), ...
    training_phases(:), ...
    phase_labels(:), ...
    dominant_data(:), ...
    subordinate_data(:), ...
    dominant_data(:) + subordinate_data(:), ...
    dominant_data(:) ./ (dominant_data(:) + subordinate_data(:)), ...
    subordinate_data(:) ./ (dominant_data(:) + subordinate_data(:)), ...
    'VariableNames', ...
    {'SexGroup','Behavior','TrainingPhase','PhaseLabel', ...
    'DominantCount','SubordinateCount','TotalCount', ...
    'PropDominant','PropSubordinate'});

source_data = [source_data; T];

end

function [stats_table, p_binom, p_chi] = plot_one_section(fd, hoy, colors, sex_group, behavior, training_phases, phase_labels, dominant_data, subordinate_data, title_name, figname, stats_table)

figure('Position', [100, 100, 400, 400]);

b = bar(training_phases, [dominant_data' subordinate_data'], ...
    'stacked', ...
    'BarWidth', 0.5);

b(1).FaceColor = 'flat';
b(1).CData = repmat(colors(1,:), length(training_phases), 1);

b(2).FaceColor = 'flat';
b(2).CData = repmat(colors(2,:), length(training_phases), 1);

ylim([0 max(dominant_data + subordinate_data) + 2]);

xlabel('Time of social rank determination (training phase)');
ylabel('Number of animals', 'FontSize', 12);

title(title_name, 'FontSize', 12);

set(gca, 'XTick', training_phases);
set(gca, 'XTickLabel', phase_labels);
set(gca, 'TickDir', 'out', 'FontSize',20);

legend({'Dominant', 'Subordinate'}, ...
       'Location', 'northoutside', ...
       'Orientation', 'horizontal', ...
       'FontSize', 20);

print(gcf, figname, '-dpdf');

p_binom = nan(numel(training_phases),1);

fprintf('\n========================================\n')
fprintf('%s | %s\n', sex_group, behavior)
fprintf('========================================\n')

fprintf('\nBinomial test at each stage against 0.5\n')

for i = 1:numel(training_phases)

    n_i = dominant_data(i) + subordinate_data(i);
    k_i = min(dominant_data(i), subordinate_data(i));

    p_i = 2 * binocdf(k_i, n_i, 0.5);
    p_i = min(p_i, 1);

    p_binom(i) = p_i;

    fprintf('Phase %s: Dominant = %d, Subordinate = %d, Total = %d, P = %.6g\n', ...
        phase_labels{i}, dominant_data(i), subordinate_data(i), n_i, p_i)

end

observed = [dominant_data; subordinate_data]';

total = sum(observed, 'all');
row_totals = sum(observed, 2);
col_totals = sum(observed, 1);
expected = (row_totals * col_totals) ./ total;

chi2_stat = sum(((observed - expected).^2) ./ expected, 'all');
df = (size(observed, 1) - 1) * (size(observed, 2) - 1);
p_chi = 1 - chi2cdf(chi2_stat, df);

fprintf('\nChi-square test across stages\n')
fprintf('Chi-square statistic = %.4f\n', chi2_stat)
fprintf('Degrees of freedom = %d\n', df)
fprintf('P = %.6g\n', p_chi)

T_binom = table( ...
    repmat({sex_group}, numel(training_phases), 1), ...
    repmat({behavior}, numel(training_phases), 1), ...
    repmat({'DominantVsSubordinate'}, numel(training_phases), 1), ...
    repmat({'two-tailed binomial test against 0.5'}, numel(training_phases), 1), ...
    training_phases(:), ...
    phase_labels(:), ...
    dominant_data(:) + subordinate_data(:), ...
    dominant_data(:), ...
    subordinate_data(:), ...
    nan(numel(training_phases),1), ...
    nan(numel(training_phases),1), ...
    p_binom(:), ...
    'VariableNames', ...
    {'SexGroup','Behavior','Comparison','Test', ...
    'TrainingPhase','PhaseLabel','N','DominantCount','SubordinateCount', ...
    'ChiSquare','DF','PValue'});

T_chi = table( ...
    {sex_group}, ...
    {behavior}, ...
    {'ChangeAcrossStages'}, ...
    {'chi-square test of independence'}, ...
    NaN, ...
    {'All'}, ...
    total, ...
    sum(dominant_data), ...
    sum(subordinate_data), ...
    chi2_stat, ...
    df, ...
    p_chi, ...
    'VariableNames', ...
    {'SexGroup','Behavior','Comparison','Test', ...
    'TrainingPhase','PhaseLabel','N','DominantCount','SubordinateCount', ...
    'ChiSquare','DF','PValue'});

stats_table = [stats_table; T_binom; T_chi];

end