function plt_leader_SI_demo(fd)
% Leadership SI summary
%
% Outputs to base workspace:
%   source_data
%   stats_table

mrtable = load([fd 'Data/mrtable_leadership_selfarr_selfarr+30_regout_spd&pos_self.mat']).mrtable;

params.pcut = 0.05;
params.time_bin = {'selfarr';'selfarr+30'}; 
params.fd = fd;

source_data = table();
stats_table = table();

%% leader cells
sel_leader = strcmp(mrtable.role,'leader');
mrtable_lead = mrtable(sel_leader,:);

params.role = 'leader';
plt_leadership_stats_v1(mrtable_lead,params);

sig_lead = mrtable_lead.p_leader < params.pcut;

T_lead = table( ...
    repmat({'leader'},height(mrtable_lead),1), ...
    (1:height(mrtable_lead))', ...
    mrtable_lead.SI_leader_data, ...
    mrtable_lead.p_leader, ...
    sig_lead, ...
    mrtable_lead.SI_leader_data > 0, ...
    mrtable_lead.SI_leader_data < 0, ...
    abs(mrtable_lead.SI_leader_data), ...
    'VariableNames', ...
    {'Role','CellIndex','SI','PValue','Significant', ...
    'PositiveSI','NegativeSI','AbsSI'});

source_data = [source_data; T_lead];

x_lead_pos = sum(sig_lead & mrtable_lead.SI_leader_data > 0);
x_lead_neg = sum(sig_lead & mrtable_lead.SI_leader_data < 0);
n_lead = height(mrtable_lead);

[p_lead_ztest,z_lead] = ztest(x_lead_pos,n_lead,x_lead_neg,n_lead);

fprintf('\n========================================\n')
fprintf('Leadership SI | leader cells\n')
fprintf('========================================\n')
fprintf('N cells = %d\n', n_lead)
fprintf('N significant = %d\n', sum(sig_lead))
fprintf('Proportion significant = %.4f\n', mean(sig_lead))
fprintf('N significant positive SI = %d\n', x_lead_pos)
fprintf('N significant negative SI = %d\n', x_lead_neg)
fprintf('Proportion significant positive SI = %.4f\n', x_lead_pos/n_lead)
fprintf('Proportion significant negative SI = %.4f\n', x_lead_neg/n_lead)
fprintf('ztest positive vs negative: z = %.4f, p = %.6g\n', z_lead, p_lead_ztest)

T_stat_lead = table( ...
    {'leader'}, ...
    n_lead, ...
    sum(sig_lead), ...
    mean(sig_lead), ...
    x_lead_pos, ...
    x_lead_neg, ...
    x_lead_pos/n_lead, ...
    x_lead_neg/n_lead, ...
    z_lead, ...
    p_lead_ztest, ...
    'VariableNames', ...
    {'Role','NCells','NSignificant','PropSignificant', ...
    'NPositiveSignificant','NNegativeSignificant', ...
    'PropPositiveSignificant','PropNegativeSignificant', ...
    'Z_PosVsNeg','P_PosVsNeg'});

stats_table = [stats_table; T_stat_lead];

%% follower cells
sel_follower = strcmp(mrtable.role,'follower');
mrtable_foll = mrtable(sel_follower,:);

params.role = 'follower';
plt_leadership_stats_v1(mrtable_foll,params);

sig_foll = mrtable_foll.p_leader < params.pcut;

T_foll = table( ...
    repmat({'follower'},height(mrtable_foll),1), ...
    (1:height(mrtable_foll))', ...
    mrtable_foll.SI_leader_data, ...
    mrtable_foll.p_leader, ...
    sig_foll, ...
    mrtable_foll.SI_leader_data > 0, ...
    mrtable_foll.SI_leader_data < 0, ...
    abs(mrtable_foll.SI_leader_data), ...
    'VariableNames', ...
    {'Role','CellIndex','SI','PValue','Significant', ...
    'PositiveSI','NegativeSI','AbsSI'});

source_data = [source_data; T_foll];

x_foll_pos = sum(sig_foll & mrtable_foll.SI_leader_data > 0);
x_foll_neg = sum(sig_foll & mrtable_foll.SI_leader_data < 0);
n_foll = height(mrtable_foll);

[p_foll_ztest,z_foll] = ztest(x_foll_pos,n_foll,x_foll_neg,n_foll);

fprintf('\n========================================\n')
fprintf('Leadership SI | follower cells\n')
fprintf('========================================\n')
fprintf('N cells = %d\n', n_foll)
fprintf('N significant = %d\n', sum(sig_foll))
fprintf('Proportion significant = %.4f\n', mean(sig_foll))
fprintf('N significant positive SI = %d\n', x_foll_pos)
fprintf('N significant negative SI = %d\n', x_foll_neg)
fprintf('Proportion significant positive SI = %.4f\n', x_foll_pos/n_foll)
fprintf('Proportion significant negative SI = %.4f\n', x_foll_neg/n_foll)
fprintf('ztest positive vs negative: z = %.4f, p = %.6g\n', z_foll, p_foll_ztest)

T_stat_foll = table( ...
    {'follower'}, ...
    n_foll, ...
    sum(sig_foll), ...
    mean(sig_foll), ...
    x_foll_pos, ...
    x_foll_neg, ...
    x_foll_pos/n_foll, ...
    x_foll_neg/n_foll, ...
    z_foll, ...
    p_foll_ztest, ...
    'VariableNames', ...
    {'Role','NCells','NSignificant','PropSignificant', ...
    'NPositiveSignificant','NNegativeSignificant', ...
    'PropPositiveSignificant','PropNegativeSignificant', ...
    'Z_PosVsNeg','P_PosVsNeg'});

stats_table = [stats_table; T_stat_foll];

%% leader vs follower abs(SI)
[p_rank,h_rank,stats_rank] = ranksum(abs(mrtable_lead.SI_leader_data), ...
                                     abs(mrtable_foll.SI_leader_data));

ranksum_stat = NaN;
z_rank = NaN;

if isfield(stats_rank,'ranksum')
    ranksum_stat = stats_rank.ranksum;
end

if isfield(stats_rank,'zval')
    z_rank = stats_rank.zval;
end

fprintf('\n========================================\n')
fprintf('Abs leadership SI | leader vs follower cells\n')
fprintf('========================================\n')
fprintf('Test: Wilcoxon rank-sum test\n')
fprintf('Leader N = %d\n', n_lead)
fprintf('Follower N = %d\n', n_foll)
fprintf('Leader median abs(SI) = %.4f\n', median(abs(mrtable_lead.SI_leader_data),'omitnan'))
fprintf('Follower median abs(SI) = %.4f\n', median(abs(mrtable_foll.SI_leader_data),'omitnan'))
fprintf('Ranksum statistic = %.4f\n', ranksum_stat)
if ~isnan(z_rank)
    fprintf('Z = %.4f\n', z_rank)
end
fprintf('P = %.6g\n', p_rank)

T_rank = table( ...
    {'leader_vs_follower_absSI'}, ...
    {'ranksum'}, ...
    n_lead, ...
    n_foll, ...
    median(abs(mrtable_lead.SI_leader_data),'omitnan'), ...
    median(abs(mrtable_foll.SI_leader_data),'omitnan'), ...
    ranksum_stat, ...
    z_rank, ...
    p_rank, ...
    'VariableNames', ...
    {'Comparison','Test','NLeader','NFollower', ...
    'MedianAbsSI_Leader','MedianAbsSI_Follower', ...
    'RankSumStatistic','Z','PValue'});

stats_rank_table = T_rank;
assignin('base','source_data',source_data);
assignin('base','stats_table',stats_table);
assignin('base','stats_rank_table',stats_rank_table);

fprintf('\nSaved to base workspace:\n')
fprintf('source_data\n')
fprintf('stats_table\n')

end