function fig = plt_swap_learning(fd)
% compare days to criterion between original pair and swapped pair
%
% Outputs to base workspace:
%   source_data_swap_learning
%   stats_table_swap_learning

hoy = char(datetime('now','Format','yyyyMMdd'));

plot_dir = fullfile(fd,'plots');
if ~exist(plot_dir,'dir')
    mkdir(plot_dir);
end

source_data_swap_learning = table();
stats_table_swap_learning = table();

%% both sexes
original_training = [13, 3, 21, 50, 14, 18, 8, 10, 33, 6, 18, 32, 7, 43, 4, 9];
swapped_training = [1, 2, 1, 8, 8, 9, 8, 1, 3, 2, 23, 1, 12, 1, 1, 1];

[fig, source_data_swap_learning, stats_table_swap_learning] = plot_one_swap_learning( ...
    original_training, swapped_training, ...
    'all', [0.2 0.2 0.2], ...
    'Swapped learning', ...
    fullfile(plot_dir,[hoy '_swap_cumu_learning']), ...
    source_data_swap_learning, stats_table_swap_learning);

%% females
fill_colors = [239,154,154;129, 212, 250]/255;
line_colors = [183, 28, 28;1, 87, 155]/255;

original_training_female = [21, 50, 8, 10, 33, 6, 7, 43, 4, 9];
swapped_training_female = [1, 8, 8, 1, 3, 2, 12, 1, 1, 1];

[fig, source_data_swap_learning, stats_table_swap_learning] = plot_one_swap_learning( ...
    original_training_female, swapped_training_female, ...
    'female', line_colors(1,:), ...
    'Swapped learning', ...
    fullfile(plot_dir,[hoy '_swap_cumu_learning_female']), ...
    source_data_swap_learning, stats_table_swap_learning);

%% males
original_training_male = [13, 3, 14, 18, 18, 32];
swapped_training_male = [1, 2, 8, 9, 23, 1];

[fig, source_data_swap_learning, stats_table_swap_learning] = plot_one_swap_learning( ...
    original_training_male, swapped_training_male, ...
    'male', line_colors(2,:), ...
    'Swapped learning', ...
    fullfile(plot_dir,[hoy '_swap_cumu_learning_male']), ...
    source_data_swap_learning, stats_table_swap_learning);

assignin('base','source_data_swap_learning',source_data_swap_learning);
assignin('base','stats_table_swap_learning',stats_table_swap_learning);

fprintf('\nSaved to base workspace:\n')
fprintf('source_data_swap_learning\n')
fprintf('stats_table_swap_learning\n')

end

function [fig, source_data, stats_table] = plot_one_swap_learning( ...
    original_training, swapped_training, sex_group, line_color, title_base, figname, source_data, stats_table)

original_training = original_training(:);
swapped_training = swapped_training(:);

n_pairs = length(original_training);

sorted_original = sort(original_training);
sorted_swapped = sort(swapped_training);

prop_original = (1:length(sorted_original))' / length(sorted_original);
prop_swapped = (1:length(sorted_swapped))' / length(sorted_swapped);

T_original = table( ...
    repmat({sex_group},length(original_training),1), ...
    (1:length(original_training))', ...
    repmat({'Original'},length(original_training),1), ...
    original_training, ...
    'VariableNames', ...
    {'SexGroup','PairIndex','Condition','DaysToCriterion'});

T_swapped = table( ...
    repmat({sex_group},length(swapped_training),1), ...
    (1:length(swapped_training))', ...
    repmat({'Swapped'},length(swapped_training),1), ...
    swapped_training, ...
    'VariableNames', ...
    {'SexGroup','PairIndex','Condition','DaysToCriterion'});

source_data = [source_data; T_original; T_swapped];

fig = figure('Position',[1000 300 400 400]);
hold on;

plot(sorted_original, prop_original, ...
    'LineStyle','-', ...
    'Marker','.', ...
    'Color',line_color, ...
    'LineWidth', 2, ...
    'MarkerSize', 16);

plot(sorted_swapped, prop_swapped, ...
    'LineStyle','--', ...
    'Marker','.', ...
    'Color',line_color, ...
    'LineWidth', 2, ...
    'MarkerSize', 16);

legend({'Original Pair', 'Swapped Pair '}, 'Location', 'southeast');
legend box off

xlabel('Days to criterion');
ylabel('Proportion of pairs');

if strcmp(sex_group,'all')
    title([title_base ' (' num2str(n_pairs) ' pairs)']);
else
    title([title_base ' (' num2str(n_pairs) ' ' sex_group ' pairs)']);
end

xlim([0 50])
hold off;

set(gca,'FontSize',24,'TickDir','out')

print(fig,figname,'-dpdf');

[h,p,ks_stat] = kstest2(original_training,swapped_training);

T_stats = table( ...
    {sex_group}, ...
    {'Original vs Swapped'}, ...
    {'two-sample Kolmogorov-Smirnov'}, ...
    n_pairs, ...
    median(original_training,'omitnan'), ...
    median(swapped_training,'omitnan'), ...
    mean(original_training,'omitnan'), ...
    mean(swapped_training,'omitnan'), ...
    ks_stat, ...
    p, ...
    h, ...
    'VariableNames', ...
    {'SexGroup','Comparison','Test','NPairs', ...
    'MedianOriginal','MedianSwapped', ...
    'MeanOriginal','MeanSwapped', ...
    'KSStatistic','PValue','RejectH'});

stats_table = [stats_table; T_stats];

fprintf('\n========================================\n')
fprintf('Swap learning | %s\n', sex_group)
fprintf('========================================\n')
fprintf('Test: two-sample Kolmogorov-Smirnov\n')
fprintf('N pairs = %d\n', n_pairs)
fprintf('Original median = %.4f, mean = %.4f\n', ...
    median(original_training,'omitnan'), mean(original_training,'omitnan'))
fprintf('Swapped median = %.4f, mean = %.4f\n', ...
    median(swapped_training,'omitnan'), mean(swapped_training,'omitnan'))
fprintf('KS statistic = %.4f\n', ks_stat)
fprintf('P = %.6g\n', p)
fprintf('Reject H = %d\n', h)
fprintf('Saved figure: %s\n', figname)

end